<a href="https://colab.research.google.com/github/jairaj023/Internship-Practice/blob/main/Cleaned_sales_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import pandas as pd

In [84]:
import numpy as np

In [85]:
import matplotlib.pyplot as plt

In [86]:
from google.colab import files

uploaded = files.upload()

Saving messy_sales_data.csv to messy_sales_data (2).csv

In [87]:
df = pd.read_csv("messy_sales_data.csv")
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,Electronics,2,550,North,1100.0
1,1002.0,2026/01/06,Bob,Phone,Electronics,NaN,300,South,600.0
2,1003.0,05-01-2026,Charlie,Tablet,Electronics,1,abc,East,400.0
3,1004.0,NaN,David,Headphones,Electronics,3,50,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550,North,1100.0

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    14 non-null     float64
 1   Date        14 non-null     object
 2   Customer    15 non-null     object
 3   Product     14 non-null     object
 4   Category    15 non-null     object
 5   Quantity    14 non-null     object
 6   Unit_Price  14 non-null     object
 7   Region      15 non-null     object
 8   Sales       14 non-null     float64
dtypes: float64(2), object(7)
memory usage: 1.2+ KB

In [89]:
df.describe().round()//len(df)*100

       Order_ID      Sales
count       0.0        0.0
mean     6700.0    98200.0
std         0.0   355500.0
min      6600.0     -800.0
25%      6600.0     1200.0
50%      6700.0     3000.0
75%      6700.0     6500.0
max      6700.0  1333300.0

In [90]:
df.isnull().sum()

Order_ID      1
Date          1
Customer      0
Product       1
Category      0
Quantity      1
Unit_Price    1
Region        0
Sales         1
dtype: int64

In [91]:
df.shape

(15, 9)

In [92]:
df.dropna().shape

(10, 9)

In [93]:
df[df.duplicated()].shape

(1, 9)

In [94]:
df[df.duplicated()]

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
5,1005.0,2026-01-09,Alice,Laptop,electronics,2,550,North,1100.0

In [95]:
df['Order_ID'].value_counts().head(10)

Order_ID
1005.0    2
1001.0    1
1002.0    1
1003.0    1
1004.0    1
1006.0    1
1007.0    1
1008.0    1
1009.0    1
1010.0    1
Name: count, dtype: int64

In [96]:
df[df['Order_ID'] == '1005.0']

Empty DataFrame
Columns: [Order_ID, Date, Customer, Product, Category, Quantity, Unit_Price, Region, Sales]
Index: []

In [97]:
for col in df.columns:
  if df[col].nunique() < 20:
    print(col)
    print(df[col].value_counts())
    print('-'*50)

Order_ID
Order_ID
1005.0    2
1001.0    1
1002.0    1
1003.0    1
1004.0    1
1006.0    1
1007.0    1
1008.0    1
1009.0    1
1010.0    1
1012.0    1
1013.0    1
1014.0    1
Name: count, dtype: int64
--------------------------------------------------
Date
Date
2026-01-09    2
2026-01-05    1
2026/01/06    1
05-01-2026    1
2026-01-10    1
2026-01-11    1
2026-01-12    1
2026-01-13    1
2026-13-01    1
2026-01-15    1
2026-01-16    1
2026-01-17    1
2026-01-18    1
Name: count, dtype: int64
--------------------------------------------------
Customer
Customer
Alice      2
Alice      1
Bob        1
Charlie    1
David      1
Eve        1
Frank      1
Grace      1
Heidi      1
Ivan       1
Judy       1
Mallory    1
Oscar      1
Peggy      1
Name: count, dtype: int64
--------------------------------------------------
Product
Product
Laptop        3
Phone         2
Tablet        1
Headphones    1
Chair         1
Desk          1
Monitor       1
Mouse         1
Keyboard      1
Printer       1
Camera        1
Name: count, dtype: int64
--------------------------------------------------
Category
Category
Electronics    10
Furniture       3
electronics     2
Name: count, dtype: int64
--------------------------------------------------
Quantity
Quantity
2       6
1       2
3       2
-1      1
4       1
1000    1
two     1
Name: count, dtype: int64
--------------------------------------------------
Unit_Price
Unit_Price
550    3
300    2
abc    1
50     1
120    1
80     1
200    1
25     1
40     1
150    1
500    1
Name: count, dtype: int64
--------------------------------------------------
Region
Region
North      4
South      4
East       3
West       2
Unknown    1
           1
Name: count, dtype: int64
--------------------------------------------------
Sales
Sales
 1100.0      3
 600.0       1
 400.0       1
 150.0       1
-120.0       1
 320.0       1
 200000.0    1
 75.0        1
 80.0        1
 300.0       1
 500.0       1
 650.0       1
Name: count, dtype: int64
--------------------------------------------------

**Handling Missing Values**

In [98]:
df.dropna(subset=['Order_ID'],inplace = True)

In [99]:
df.isnull().sum()

Order_ID      0
Date          1
Customer      0
Product       1
Category      0
Quantity      1
Unit_Price    1
Region        0
Sales         1
dtype: int64

In [100]:
df['Date'].unique()

array(['2026-01-05', '2026/01/06', '05-01-2026', nan, '2026-01-09',
       '2026-01-10', '2026-01-11', '2026-01-12', '2026-01-13',
       '2026-13-01', '2026-01-16', '2026-01-17', '2026-01-18'],
      dtype=object)

In [101]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,Electronics,2,550,North,1100.0
1,1002.0,2026/01/06,Bob,Phone,Electronics,NaN,300,South,600.0
2,1003.0,05-01-2026,Charlie,Tablet,Electronics,1,abc,East,400.0
3,1004.0,NaN,David,Headphones,Electronics,3,50,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550,North,1100.0

In [102]:
df['Category'] = df['Category'].str.lower().str.strip()

In [103]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550,North,1100.0
1,1002.0,2026/01/06,Bob,Phone,electronics,NaN,300,South,600.0
2,1003.0,05-01-2026,Charlie,Tablet,electronics,1,abc,East,400.0
3,1004.0,NaN,David,Headphones,electronics,3,50,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550,North,1100.0

In [104]:
df.duplicated().shape

(14,)

In [105]:
df.drop_duplicates(inplace=True)

In [106]:
df.duplicated().shape

(13,)

In [107]:
df[df['Customer'] == 'Alice']

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550,North,1100.0

In [108]:
df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors='coerce')
median_price = df['Unit_Price'].median()
df['Unit_Price'].fillna(median_price, inplace=True)
df[['Unit_Price']].head()

/tmp/ipykernel_3020/3944276216.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unit_Price'].fillna(median_price, inplace=True)

   Unit_Price
0       550.0
1       300.0
2       200.0
3        50.0
4       550.0

In [109]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550.0,North,1100.0
1,1002.0,2026/01/06,Bob,Phone,electronics,NaN,300.0,South,600.0
2,1003.0,05-01-2026,Charlie,Tablet,electronics,1,200.0,East,400.0
3,1004.0,NaN,David,Headphones,electronics,3,50.0,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550.0,North,1100.0

In [110]:
df['Quantity'].fillna(df['Quantity'].mode()[0], inplace=True)

/tmp/ipykernel_3020/105620981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mode()[0], inplace=True)

In [111]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550.0,North,1100.0
1,1002.0,2026/01/06,Bob,Phone,electronics,2,300.0,South,600.0
2,1003.0,05-01-2026,Charlie,Tablet,electronics,1,200.0,East,400.0
3,1004.0,NaN,David,Headphones,electronics,3,50.0,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550.0,North,1100.0

In [131]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='mixed')

In [124]:
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [128]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550.0,North,1100.0
1,1002.0,2026-01-06,Bob,Phone,electronics,2,300.0,South,600.0
2,1003.0,2026-05-01,Charlie,Tablet,electronics,1,200.0,East,400.0
3,1004.0,2026-01-05,David,Headphones,electronics,3,50.0,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550.0,North,1100.0

In [127]:
df['Date'].fillna(df['Date'].mode()[0], inplace=True)

/tmp/ipykernel_3020/410165322.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna(df['Date'].mode()[0], inplace=True)

In [129]:
df.head()

,Order_ID,Date,Customer,Product,Category,Quantity,Unit_Price,Region,Sales
0,1001.0,2026-01-05,Alice,Laptop,electronics,2,550.0,North,1100.0
1,1002.0,2026-01-06,Bob,Phone,electronics,2,300.0,South,600.0
2,1003.0,2026-05-01,Charlie,Tablet,electronics,1,200.0,East,400.0
3,1004.0,2026-01-05,David,Headphones,electronics,3,50.0,West,150.0
4,1005.0,2026-01-09,Alice,Laptop,electronics,2,550.0,North,1100.0

In [133]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='mixed')

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 14
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    13 non-null     float64
 1   Date        13 non-null     datetime64[ns]
 2   Customer    13 non-null     object
 3   Product     12 non-null     object
 4   Category    13 non-null     object
 5   Quantity    13 non-null     object
 6   Unit_Price  13 non-null     float64
 7   Region      13 non-null     object
 8   Sales       12 non-null     float64
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 1.6+ KB

In [134]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 14
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    13 non-null     float64
 1   Date        13 non-null     datetime64[ns]
 2   Customer    13 non-null     object
 3   Product     12 non-null     object
 4   Category    13 non-null     object
 5   Quantity    12 non-null     float64
 6   Unit_Price  13 non-null     float64
 7   Region      13 non-null     object
 8   Sales       12 non-null     float64
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 1.6+ KB

In [137]:
df.to_csv('cleaned_sales_data.csv', index=False)

In [138]:
files.download('cleaned_sales_data.csv')