<a href="https://colab.research.google.com/github/jairaj023/Internship-Practice/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from google.colab import files
upload = files.upload()

Saving raw_jobs.csv to raw_jobs.csv

In [5]:
df = pd.read_csv('raw_jobs.csv')

In [6]:
df.head(9)

,job_id,job_title,company,location,job_description,experience,education,salary,job_type
0,JOB00001,Python Developer,Infosys,Remote,We are looking for a Python Developer to join ...,1-3 years,MCA,₹10-16 LPA,Part-time
1,JOB00002,Data Scientist,Infosys,"Hyderabad, Telangana",We are looking for a Data Scientist to join ou...,0-2 years,MCA,₹12-20 LPA,Remote
2,JOB00003,Data Engineer,IBM,"Bengaluru, Karnataka",We are looking for a Data Engineer to join our...,8-12 years,BCA,₹3-5 LPA,Internship
3,JOB00004,Business Analyst,Google,"Hyderabad, Telangana",We are looking for a Business Analyst to join ...,1-3 years,M.Tech,₹10-16 LPA,Remote
4,JOB00005,Business Analyst,Mphasis,"Delhi, India",We are looking for a Business Analyst to join ...,8-12 years,M.Tech,₹5-8 LPA,Remote
5,JOB00006,Software Engineer,Wipro,"Mumbai, Maharashtra",We are looking for a Software Engineer to join...,8-12 years,B.Tech,₹8-12 LPA,Internship
6,JOB00007,Frontend Developer,IBM,Remote,We are looking for a Frontend Developer to joi...,5-8 years,B.Tech,₹6-10 LPA,Remote
7,JOB00008,AI Engineer,Capgemini,"Kolkata, West Bengal",We are looking for a AI Engineer to join our t...,1-3 years,Bachelor's Degree,₹3-5 LPA,Part-time
8,JOB00009,Frontend Developer,Persistent Systems,Remote,We are looking for a Frontend Developer to joi...,1-3 years,MCA,₹5-8 LPA,Internship

In [7]:
print(df.columns)

Index(['job_id', 'job_title', 'company', 'location', 'job_description',
       'experience', 'education', 'salary', 'job_type'],
      dtype='object')

In [8]:
print("Missing Job Descriptions : ", df['job_description'].isna().sum())

Missing Job Descriptions :  0

In [10]:
import re
def clean_text(text):
  text = str(text)

  text = re.sub(r"<.*?", " ", text)
  text = re.sub(r"http\S+", "", text)
  text = re.sub(r"\S+@\S+", "", text)
  text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
  text = re.sub(r"\s+", " ", text)
  text = text.strip().lower()

  return text

In [11]:
df['clean_description'] = df['job_description'].apply(clean_text)

In [12]:
df[['clean_description', 'job_description']].head(10)

,clean_description,job_description
0,we are looking for a python developer to join ...,We are looking for a Python Developer to join ...
1,we are looking for a data scientist to join ou...,We are looking for a Data Scientist to join ou...
2,we are looking for a data engineer to join our...,We are looking for a Data Engineer to join our...
3,we are looking for a business analyst to join ...,We are looking for a Business Analyst to join ...
4,we are looking for a business analyst to join ...,We are looking for a Business Analyst to join ...
5,we are looking for a software engineer to join...,We are looking for a Software Engineer to join...
6,we are looking for a frontend developer to joi...,We are looking for a Frontend Developer to joi...
7,we are looking for a ai engineer to join our t...,We are looking for a AI Engineer to join our t...
8,we are looking for a frontend developer to joi...,We are looking for a Frontend Developer to joi...
9,we are looking for a ai engineer to join our t...,We are looking for a AI Engineer to join our t...

In [13]:
df = df.drop_duplicates(subset = ['clean_description'])

In [14]:
df = df[df['clean_description'].str.strip() != ""]

In [15]:
df = df.reset_index(drop = True)

In [16]:
df.to_csv('clean_job.csv', index = True)

In [17]:
print("Cleaning completed successfully!")
print("Total rows:", len(df))
print("Columns:", df.columns.tolist())

Cleaning completed successfully!
Total rows: 9993
Columns: ['job_id', 'job_title', 'company', 'location', 'job_description', 'experience', 'education', 'salary', 'job_type', 'clean_description']

In [18]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type,clean_description
0,JOB00001,Python Developer,Infosys,Remote,We are looking for a Python Developer to join ...,1-3 years,MCA,₹10-16 LPA,Part-time,we are looking for a python developer to join ...
1,JOB00002,Data Scientist,Infosys,"Hyderabad, Telangana",We are looking for a Data Scientist to join ou...,0-2 years,MCA,₹12-20 LPA,Remote,we are looking for a data scientist to join ou...
2,JOB00003,Data Engineer,IBM,"Bengaluru, Karnataka",We are looking for a Data Engineer to join our...,8-12 years,BCA,₹3-5 LPA,Internship,we are looking for a data engineer to join our...
3,JOB00004,Business Analyst,Google,"Hyderabad, Telangana",We are looking for a Business Analyst to join ...,1-3 years,M.Tech,₹10-16 LPA,Remote,we are looking for a business analyst to join ...
4,JOB00005,Business Analyst,Mphasis,"Delhi, India",We are looking for a Business Analyst to join ...,8-12 years,M.Tech,₹5-8 LPA,Remote,we are looking for a business analyst to join ...